### ISSUE TITLE
构建docker镜像成功，但是无法启动容器

### ISSUE THREAD

**Issue by spysir** [arugal/frp-notify#27]
还有请问一下大佬，docker镜像的volume路径是什么？

**Comment by arugal** [comment]
你现在使用的哪个镜像？我已经很久没维护镜像了

**Comment by spysir** [comment]
> 你现在使用的哪个镜像？我已经很久没维护镜像了

刚刚用你最新的源码构建的docker镜像

**Comment by arugal** [comment]
那你的 dockerfile 呢？容器启动的日志是怎样的？

**Comment by spysir** [comment]
> 



> 那你的 dockerfile 呢？容器启动的日志是怎样的？

用你源码中的dockerfile

**Comment by arugal** [comment]
那你提供日志看看

**Comment by spysir** [comment]
> 

docker logs -f frp-notify 没有看到有日志输出，docker ps -a 容器状态显示restarting

**Comment by arugal** [comment]
@spysir 我更新了一下 dockerfile, 你可以直接使用 `docker pull ghcr.io/arugal/frp-notify/frp-notify:latest`

**Comment by spysir** [comment]
> @spysir 我更新了一下 dockerfile, 你可以直接使用 `docker pull ghcr.io/arugal/frp-notify/frp-notify:latest`

无法加载配置文件，请问大佬volume的路径是什么？
![Snipaste_2022-09-04_15-18-59](https://user-images.githubusercontent.com/59646715/188302309-1946ce19-8c01-4470-bdd1-cebfd16026b2.jpg)
