### ISSUE TITLE
无法加载配置文件，请问大佬容器volume的路径是什么？

### ISSUE THREAD

**Issue by spysir** [arugal/frp-notify#29]
![Snipaste_2022-09-04_15-18-59](https://user-images.githubusercontent.com/59646715/188302711-7d77f2eb-6cc3-4c67-8c5d-02ff084d28d8.jpg)

**Comment by arugal** [comment]
`docker run -d -p 58080:80 -v $(pwd)/frp-notify.json:/frp-notify.json ghcr.io/arugal/frp-notify/frp-notify:latest`
