### ISSUE TITLE
no such notify lark

### ISSUE THREAD

**Issue by star-journey** [arugal/frp-notify#35]
Here is my config: 
```json
"notify_plugins": [
    {
      "name": "lark",
      "config": {
        "webhook_url": "",
        "secret": "",
        "at_users": []
      }
    }, 
    {
      "name": "dingTalk",                                                               
      "config": {
        "token": "",    
        "secret": "",  
        "is_at_all": true                                                              
      }
    }
  ]
```
Then, when I start, it reports: 
- "ERROR init notify err : no such notify, cfg: {lark map[at_users:[] secret: webhook_url:]}";
- "ERROR init notify err : miss token, cfg: {dingTalk map[is_at_all:true secret: token:]}". 

Even if I set the "webhook_url", "secret" and "at_users", it still reports "ERROR init notify err : no such notify, cfg: {lark map[at_users:[xxx] secret:xxx webhook_url:xxx]}"

**Comment by rainbend** [comment]
Hi, the new version [v0.4.0](https://github.com/arugal/frp-notify/releases/tag/v0.4.0), which includes lark, has been released. Please download it again.
