### ISSUE TITLE
UDP连接没有显示

### ISSUE THREAD

**Issue by haojie06** [arugal/frp-notify#7]
作者你好，我在使用该插件的时候发现，我用frp映射了Minecraft的端口（使用udp），但是玩家连接的时候并没有显示提示信息

**Comment by arugal** [comment]
你好, @haojie06 这个需要在frp中实现，https://github.com/fatedier/frp/blob/master/doc/server_plugin_zh.md#newuserconn 这个是当时我实现时frp支持的用户连接类型

**Comment by haojie06** [comment]
好吧。谢谢回复了

**Comment by haojie06** [comment]
他这里面好像还不支持udp对吧。

**Comment by arugal** [comment]
是的, 暂时udp和stcp类型的连接都不支持。需要在frp中实现这个功能

**Comment by arugal** [comment]
@haojie06 https://github.com/fatedier/frp/pull/1740/files 这是我当时实现`NewUserConn`的PR, 供你参考

**Comment by haojie06** [comment]
明白了，谢谢
